# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from arista.inventory.v1.services import gen_pb2 as arista_dot_inventory_dot_v1_dot_services_dot_gen__pb2


class DeviceServiceStub(object):
    """Missing associated documentation comment in .proto file"""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetOne = channel.unary_unary(
                '/arista.inventory.v1.DeviceService/GetOne',
                request_serializer=arista_dot_inventory_dot_v1_dot_services_dot_gen__pb2.DeviceRequest.SerializeToString,
                response_deserializer=arista_dot_inventory_dot_v1_dot_services_dot_gen__pb2.DeviceResponse.FromString,
                )
        self.GetAll = channel.unary_stream(
                '/arista.inventory.v1.DeviceService/GetAll',
                request_serializer=arista_dot_inventory_dot_v1_dot_services_dot_gen__pb2.DeviceStreamRequest.SerializeToString,
                response_deserializer=arista_dot_inventory_dot_v1_dot_services_dot_gen__pb2.DeviceStreamResponse.FromString,
                )
        self.Subscribe = channel.unary_stream(
                '/arista.inventory.v1.DeviceService/Subscribe',
                request_serializer=arista_dot_inventory_dot_v1_dot_services_dot_gen__pb2.DeviceStreamRequest.SerializeToString,
                response_deserializer=arista_dot_inventory_dot_v1_dot_services_dot_gen__pb2.DeviceStreamResponse.FromString,
                )


class DeviceServiceServicer(object):
    """Missing associated documentation comment in .proto file"""

    def GetOne(self, request, context):
        """GetOne returns a unary model as specified by the key in the request.
        The key must be provided and all fields populated (unless otherwise specified).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAll(self, request, context):
        """GetAll returns all entities for this model, with optional filtering.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Subscribe(self, request, context):
        """Subscribe first returns all initial state known to the system,
        then will send deltas as entities are changed.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DeviceServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetOne': grpc.unary_unary_rpc_method_handler(
                    servicer.GetOne,
                    request_deserializer=arista_dot_inventory_dot_v1_dot_services_dot_gen__pb2.DeviceRequest.FromString,
                    response_serializer=arista_dot_inventory_dot_v1_dot_services_dot_gen__pb2.DeviceResponse.SerializeToString,
            ),
            'GetAll': grpc.unary_stream_rpc_method_handler(
                    servicer.GetAll,
                    request_deserializer=arista_dot_inventory_dot_v1_dot_services_dot_gen__pb2.DeviceStreamRequest.FromString,
                    response_serializer=arista_dot_inventory_dot_v1_dot_services_dot_gen__pb2.DeviceStreamResponse.SerializeToString,
            ),
            'Subscribe': grpc.unary_stream_rpc_method_handler(
                    servicer.Subscribe,
                    request_deserializer=arista_dot_inventory_dot_v1_dot_services_dot_gen__pb2.DeviceStreamRequest.FromString,
                    response_serializer=arista_dot_inventory_dot_v1_dot_services_dot_gen__pb2.DeviceStreamResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'arista.inventory.v1.DeviceService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class DeviceService(object):
    """Missing associated documentation comment in .proto file"""

    @staticmethod
    def GetOne(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/arista.inventory.v1.DeviceService/GetOne',
            arista_dot_inventory_dot_v1_dot_services_dot_gen__pb2.DeviceRequest.SerializeToString,
            arista_dot_inventory_dot_v1_dot_services_dot_gen__pb2.DeviceResponse.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetAll(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/arista.inventory.v1.DeviceService/GetAll',
            arista_dot_inventory_dot_v1_dot_services_dot_gen__pb2.DeviceStreamRequest.SerializeToString,
            arista_dot_inventory_dot_v1_dot_services_dot_gen__pb2.DeviceStreamResponse.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Subscribe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/arista.inventory.v1.DeviceService/Subscribe',
            arista_dot_inventory_dot_v1_dot_services_dot_gen__pb2.DeviceStreamRequest.SerializeToString,
            arista_dot_inventory_dot_v1_dot_services_dot_gen__pb2.DeviceStreamResponse.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)
